/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PocoClassRouteImport } from './routes/poco-class'
import { Route as CopyProjectRouteImport } from './routes/copy-project'
import { Route as CompareDatabaseRouteImport } from './routes/compare-database'
import { Route as IndexRouteImport } from './routes/index'

const PocoClassRoute = PocoClassRouteImport.update({
  id: '/poco-class',
  path: '/poco-class',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyProjectRoute = CopyProjectRouteImport.update({
  id: '/copy-project',
  path: '/copy-project',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareDatabaseRoute = CompareDatabaseRouteImport.update({
  id: '/compare-database',
  path: '/compare-database',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare-database': typeof CompareDatabaseRoute
  '/copy-project': typeof CopyProjectRoute
  '/poco-class': typeof PocoClassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare-database': typeof CompareDatabaseRoute
  '/copy-project': typeof CopyProjectRoute
  '/poco-class': typeof PocoClassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare-database': typeof CompareDatabaseRoute
  '/copy-project': typeof CopyProjectRoute
  '/poco-class': typeof PocoClassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compare-database' | '/copy-project' | '/poco-class'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare-database' | '/copy-project' | '/poco-class'
  id: '__root__' | '/' | '/compare-database' | '/copy-project' | '/poco-class'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareDatabaseRoute: typeof CompareDatabaseRoute
  CopyProjectRoute: typeof CopyProjectRoute
  PocoClassRoute: typeof PocoClassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/poco-class': {
      id: '/poco-class'
      path: '/poco-class'
      fullPath: '/poco-class'
      preLoaderRoute: typeof PocoClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-project': {
      id: '/copy-project'
      path: '/copy-project'
      fullPath: '/copy-project'
      preLoaderRoute: typeof CopyProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-database': {
      id: '/compare-database'
      path: '/compare-database'
      fullPath: '/compare-database'
      preLoaderRoute: typeof CompareDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareDatabaseRoute: CompareDatabaseRoute,
  CopyProjectRoute: CopyProjectRoute,
  PocoClassRoute: PocoClassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
